services:
  522-milestone:
    image: rnanfuka/docker-condalock-jupyterlab:latest
    container_name: 522-milestone
    ports:
      - "8878:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true