services:
  522-milestone:
    build:
      context: .
      dockerfile: Dockerfile
    image: 522-milestone
    container_name: 522-milestone
    ports:
      - "8877:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true