services:
  522-milestone:
    image: rnanfuka/docker-condalock-jupyterlab:yonas.fix-reproducibility
    platform: linux/amd64
    container_name: 522-milestone
    ports:
      - "8889:8889"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - SERVICE=quarto