make name: 522-milestone
channels:
  - conda-forge
dependencies:
  - ucimlrepo=0.0.7
  - click=8.3.1
  - numpy=2.3.5
  - scikit-learn=1.7.2
  - python=3.13.11
  - pandas=2.3.3
  - click=8.3.1
  - ipykernel=7.1.0
  - matplotlib=3.10.8
  - requests=2.32.5
  - pandera=0.27.0
  - quarto=1.8.26 # Remove this if you are building conda environment locally
  - tabulate=0.9.0
  - jupyter=1.1.1
  - pip=25.3
  - pip:
    - vegafusion
    - altair
    - vl-convert-python
    - pyarrow

