name: 522-milestone
channels:
  - conda-forge
dependencies:
  - altair
  - python
  - matplotlib
  - scikit-learn
  - vegafusion
  - ucimlrepo
  - ipykernel
  - numpy
  - pandas
  - jupyterlab
  - vl-convert-python
  - pyarrow
